name: yolov7
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - blas=1.0=mkl
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2025.2.25=haa95532_0
  - certifi=2025.4.26=py310haa95532_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cuda=11.6.2=0
  - cuda-cccl=11.6.55=0
  - cuda-command-line-tools=11.6.2=0
  - cuda-compiler=11.6.2=0
  - cuda-cudart=11.6.55=0
  - cuda-cudart-dev=11.6.55=0
  - cuda-cuobjdump=11.6.124=0
  - cuda-cupti=11.6.124=0
  - cuda-cuxxfilt=11.6.124=0
  - cuda-demo-suite=12.4.127=0
  - cuda-documentation=12.4.127=0
  - cuda-libraries=11.6.2=0
  - cuda-libraries-dev=11.6.2=0
  - cuda-memcheck=11.8.86=0
  - cuda-nsight-compute=12.4.1=0
  - cuda-nvcc=11.6.124=0
  - cuda-nvdisasm=12.5.39=0
  - cuda-nvml-dev=11.6.55=0
  - cuda-nvprof=12.5.82=0
  - cuda-nvprune=11.6.124=0
  - cuda-nvrtc=11.6.124=0
  - cuda-nvrtc-dev=11.6.124=0
  - cuda-nvtx=11.6.124=0
  - cuda-nvvp=12.5.82=0
  - cuda-profiler-api=12.4.127=0
  - cuda-runtime=11.6.2=0
  - cuda-sanitizer-api=12.5.81=0
  - cuda-toolkit=11.6.2=0
  - cuda-tools=11.6.2=0
  - cuda-version=12.5=3
  - cuda-visual-tools=11.6.2=0
  - expat=2.6.2=hd77b12b_0
  - filelock=3.13.1=py310haa95532_0
  - fontconfig=2.14.1=h9c4af85_2
  - freetype=2.12.1=ha860e81_0
  - gmpy2=2.1.2=py310h7f96b67_0
  - idna=3.4=py310haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - jinja2=3.1.3=py310haa95532_0
  - jpeg=9e=h2bbff1b_1
  - lerc=3.0=hd77b12b_0
  - libcublas=11.11.3.6=0
  - libcublas-dev=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufft-dev=10.9.0.58=0
  - libcurand=10.3.4.107=0
  - libcurand-dev=10.3.4.107=0
  - libcusolver=11.4.1.48=0
  - libcusolver-dev=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libcusparse-dev=11.7.5.86=0
  - libdeflate=1.17=h2bbff1b_1
  - libffi=3.4.4=hd77b12b_0
  - libglib=2.78.4=ha17d25a_0
  - libiconv=1.16=h2bbff1b_3
  - libnpp=11.8.0.86=0
  - libnpp-dev=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libnvjpeg-dev=11.9.0.86=0
  - libpng=1.6.39=h8cc25b3_0
  - libtiff=4.5.1=hd77b12b_0
  - libuv=1.44.2=h2bbff1b_0
  - libwebp-base=1.3.2=h2bbff1b_0
  - libxml2=2.10.4=h0ad7f3c_2
  - lz4-c=1.9.4=h2bbff1b_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py310h2bbff1b_1
  - mkl_fft=1.3.8=py310h2bbff1b_0
  - mkl_random=1.2.4=py310h59b6b97_0
  - mpc=1.1.0=h7edee0f_1
  - mpfr=4.0.2=h62dcd97_1
  - mpir=3.0.0=hec2e145_1
  - mpmath=1.3.0=py310haa95532_0
  - nsight-compute=2024.2.1.2=2
  - openjpeg=2.4.0=h4fc8c34_0
  - openssl=3.0.13=h2bbff1b_2
  - pcre2=10.42=h0ff8eda_1
  - pillow=10.2.0=py310h2bbff1b_0
  - pip=23.3.1=py310haa95532_0
  - python=3.10.13=he1021f5_0
  - pytorch=1.13.1=py3.10_cuda11.6_cudnn8_0
  - pytorch-cuda=11.6=h867d48c_0
  - pytorch-mutex=1.0=cuda
  - sqlite=3.41.2=h2bbff1b_0
  - sympy=1.12=py310haa95532_0
  - tbb=2021.8.0=h59b6b97_0
  - tk=8.6.12=h2bbff1b_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.41.2=py310haa95532_0
  - xz=5.4.5=h8cc25b3_0
  - zlib=1.2.13=h8cc25b3_0
  - zstd=1.5.5=hd43e919_0
  - pip:
      - absl-py==2.1.0
      - accelerate==0.31.0
      - addict==2.4.0
      - aenum==3.1.15
      - albumentations==1.4.0
      - aliyun-python-sdk-core==2.15.0
      - aliyun-python-sdk-kms==2.16.2
      - altair==5.5.0
      - altgraph==0.17.4
      - asttokens==2.4.1
      - astunparse==1.6.3
      - attrs==23.2.0
      - autocfg==0.0.8
      - basicsr==1.3.4.9
      - blinker==1.9.0
      - brotli==1.1.0
      - build==1.0.3
      - cachetools==6.1.0
      - caffe2onnx==1.0.2
      - cattrs==23.2.3
      - cffi==1.16.0
      - chardet==5.2.0
      - chumpy==0.70
      - click==8.1.7
      - clip-interrogator==0.6.0
      - colorama==0.4.6
      - contourpy==1.2.0
      - coremltools==7.1
      - coverage==7.4.4
      - crcmod==1.7
      - cryptography==42.0.5
      - cuda-python==12.6.2.post1
      - cycler==0.12.1
      - cython==3.0.8
      - darkdetect==0.8.0
      - dataclasses==0.6
      - decorator==5.1.1
      - defusedxml==0.7.1
      - dill==0.3.8
      - docutils==0.20.1
      - einops==0.8.1
      - et-xmlfile==1.1.0
      - exceptiongroup==1.2.0
      - executing==2.0.1
      - fake-useragent==1.5.0
      - filterpy==1.4.5
      - flake8==7.0.0
      - flask==2.2.5
      - flaskwebgui==0.3.5
      - flatbuffers==25.2.10
      - fonttools==4.48.1
      - fsspec==2024.2.0
      - ftfy==6.1.3
      - future==1.0.0
      - gast==0.6.0
      - gitdb==4.0.11
      - gitpython==3.1.42
      - gluoncv==0.10.5.post0
      - google-pasta==0.2.0
      - grpcio==1.60.1
      - h5py==3.12.1
      - huggingface-hub==0.23.4
      - imageio==2.34.0
      - imageio-ffmpeg==0.6.0
      - imgviz==1.5.0
      - importlib-metadata==7.0.1
      - imread-from-url==0.1.3
      - iniconfig==2.0.0
      - interrogate==1.5.0
      - ipython==8.22.1
      - isort==4.3.21
      - itsdangerous==2.1.2
      - jaraco-classes==3.3.1
      - jedi==0.19.1
      - jmespath==0.10.0
      - joblib==1.3.2
      - json-tricks==3.17.3
      - jsonschema==4.24.0
      - jsonschema-specifications==2025.4.1
      - keras==3.8.0
      - keyring==24.3.1
      - kiwisolver==1.4.5
      - lapx==0.5.5
      - lazy-loader==0.3
      - libclang==18.1.1
      - llvmlite==0.42.0
      - lmdb==1.6.2
      - loguru==0.7.2
      - mako==1.3.8
      - markdown==3.5.2
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.8.2
      - matplotlib-inline==0.1.6
      - mccabe==0.7.0
      - mdurl==0.1.2
      - ml-dtypes==0.4.0
      - mmcv==2.1.0
      - mmdeploy==1.3.1
      - mmdet==3.3.0
      - mmengine==0.10.3
      - model-index==0.1.11
      - more-itertools==10.2.0
      - mouseinfo==0.1.3
      - moviepy==2.2.1
      - multiprocess==0.70.16
      - munkres==1.1.4
      - mutagen==1.47.0
      - namex==0.0.8
      - narwhals==1.43.1
      - natsort==8.1.0
      - networkx==3.2.1
      - nh3==0.2.15
      - nltk==3.9.1
      - numba==0.59.1
      - numpy==1.23.5
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-pyindex==1.0.9
      - onnx==1.12.0
      - onnx-clip==4.0.1
      - onnx-graphsurgeon==0.3.27
      - onnx-simplifier==0.4.35
      - onnx-tool==0.8.1
      - onnxruntime==1.15.1
      - onnxruntime-gpu==1.18.0
      - onnxscript==0.1.0.dev20240816
      - onnxsim==0.4.36
      - onnxslim==0.1.33
      - open-clip-torch==2.24.0
      - opencv-contrib-python-headless==4.7.0.72
      - opencv-python==4.9.0.80
      - opencv-python-headless==4.9.0.80
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openpyxl==3.1.2
      - openxlab==0.0.36
      - opt-einsum==3.4.0
      - optim==0.1.0
      - optree==0.14.0
      - ordered-set==4.1.0
      - oss2==2.17.0
      - packaging==23.2
      - pandas==2.2.0
      - parameterized==0.9.0
      - parso==0.8.3
      - pefile==2023.2.7
      - pkginfo==1.9.6
      - platformdirs==4.2.0
      - pluggy==1.4.0
      - portalocker==2.8.2
      - prettytable==3.10.0
      - proglog==0.1.12
      - prompt-toolkit==3.0.43
      - protobuf==3.20.1
      - psutil==5.9.8
      - pure-eval==0.2.2
      - py==1.11.0
      - py-cpuinfo==9.0.0
      - pyaml==23.12.0
      - pyarrow==20.0.0
      - pyautogui==0.9.54
      - pyclipper==1.3.0.post5
      - pycocotools==2.0.7
      - pycodestyle==2.11.1
      - pycparser==2.21
      - pycryptodome==3.20.0
      - pycryptodomex==3.20.0
      - pycuda==2024.1.2
      - pydeck==0.9.1
      - pyflakes==3.2.0
      - pygetwindow==0.0.9
      - pygments==2.17.2
      - pyinstaller==6.12.0
      - pyinstaller-hooks-contrib==2025.2
      - pymsgbox==1.0.9
      - pyparsing==3.1.1
      - pyperclip==1.8.2
      - pyproject-hooks==1.0.0
      - pyqt5==5.15.7
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.13.0
      - pyrect==0.2.0
      - pyscreeze==0.1.30
      - pytest==8.1.1
      - pytest-runner==6.0.1
      - python-dateutil==2.8.2
      - python-dotenv==1.1.0
      - python-graphviz==0.20.3
      - pytools==2024.1.21
      - pytube==11.0.0
      - pytweening==1.2.0
      - pytz==2023.4
      - pywin32==306
      - pywin32-ctypes==0.2.2
      - pyyaml==6.0.1
      - qimage2ndarray==1.10.0
      - qudida==0.0.4
      - readme-renderer==43.0
      - referencing==0.36.2
      - regex==2023.12.25
      - requests==2.32.3
      - requests-toolbelt==1.0.0
      - rfc3986==2.0.0
      - rich==13.4.2
      - rpds-py==0.25.1
      - safetensors==0.4.2
      - scikit-image==0.22.0
      - scikit-learn==1.4.1.post1
      - scipy==1.15.2
      - seaborn==0.13.2
      - sentencepiece==0.2.0
      - setuptools==69.5.1
      - shapely==2.0.3
      - shellingham==1.5.4
      - six==1.16.0
      - smmap==5.0.1
      - stack-data==0.6.3
      - streamlit==1.46.0
      - supervision==0.20.0
      - tabulate==0.9.0
      - tb-nightly==2.20.0a20250413
      - tenacity==9.1.2
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.18.0
      - tensorflow-intel==2.18.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - tensorrt==10.7.0
      - tensorrt-cu12==10.7.0
      - tensorrt-cu12-bindings==10.7.0
      - tensorrt-cu12-libs==10.7.0
      - termcolor==1.1.0
      - terminaltables==3.1.10
      - tf-keras-nightly==2.16.0.dev2024021310
      - tflite==2.10.0
      - thop==0.1.1-2209072238
      - threadpoolctl==3.3.0
      - tifffile==2024.2.12
      - timm==0.9.16
      - tokenizers==0.19.1
      - toml==0.10.2
      - tomli==2.0.1
      - torch==1.13.1
      - torchaudio==0.13.1
      - torchinfo==1.8.0
      - torchsummary==1.5.1
      - torchvision==0.14.1
      - tornado==6.5.1
      - tqdm==4.65.2
      - traitlets==5.14.1
      - transformers==4.41.2
      - twine==5.0.0
      - typer==0.12.3
      - typing-extensions==4.14.0
      - tzdata==2024.1
      - ultralytics==8.3.58
      - ultralytics-thop==2.0.13
      - urllib3==1.26.18
      - watchdog==6.0.0
      - wcwidth==0.2.13
      - websockets==12.0
      - werkzeug==3.0.1
      - whichcraft==0.6.1
      - win32-setctime==1.1.0
      - wrapt==1.17.2
      - xdoctest==1.1.3
      - xtcocotools==1.14.3
      - yacs==0.1.8
      - yapf==0.40.2
      - yt-dlp==2024.8.6
      - zipp==3.17.0
prefix: C:\Users\S1SECOM\anaconda3\envs\yolov7
